services:
  sse-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "8091:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped

  sse-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8090:8090"
    restart: unless-stopped
